version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - DATABASE_URL=postgresql${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3